export const SET_SELECTED_API = "SET_SELECTED_API";
export const CALL_GET_POLICY_API = "CALL_GET_POLICY_API";
export const GET_POLICY_API_SUCCESS = "GET_POLICY_API_SUCCESS";
export const GET_POLICY_API_FAILURE = "GET_POLICY_API_FAILURE";
export const SET_LOADING = "SET_LOADING";