export const CALL_GET_DISTRIBUTION_VERSION_API = "CALL_GET_DISTRIBUTION_VERSION_API";
export const GET_DISTRIBUTION_VERSION_API_SUCCESS = "GET_DISTRIBUTION_VERSION_API_SUCCESS";
export const GET_DISTRIBUTION_VERSION_API_FAILURE = "GET_DISTRIBUTION_VERSION_API_FAILURE";
export const CALL_GET_DEVICE_VIOLATION_API = "CALL_GET_DEVICE_VIOLATION_API";
export const GET_DEVICE_VIOLATION_API_SUCCESS = "GET_DEVICE_VIOLATION_API_SUCCESS";
export const GET_DEVICE_VIOLATION_API_FAILURE = "GET_DEVICE_VIOLATION_API_FAILURE";
