export const CALL_AUDIT_MANAGEMENT_LOG_API = "CALL_AUDIT_MANAGEMENT_LOG_API";
export const GET_AUDIT_MANAGEMENT_LOG_API_SUCCESS = "GET_AUDIT_MANAGEMENT_LOG_API_SUCCESS";
export const GET_AUDIT_MANAGEMENT_LOG_API_FAILURE = "GET_AUDIT_MANAGEMENT_LOG_API_FAILURE";
export const CALL_AUDIT_AGENT_REPORTS_API = "CALL_AUDIT_AGENT_REPORTS_API";
export const GET_AUDIT_AGENT_REPORTS_API_SUCCESS = "GET_AUDIT_AGENT_REPORTS_API_SUCCESS";
export const GET_AUDIT_AGENT_REPORTS_API_FAILURE = "GET_AUDIT_AGENT_REPORTS_API_FAILURE";